triggers:
- envs: []
  name: life_expectancy_to_gcp_load
  pipeline_uuid: life_expectancy_to_gcs_load
  schedule_interval: 5 12 * 4 *
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-03-30 13:00:00
  status: active
  variables: {}
