triggers:
- envs: []
  name: life_expectancy_to_bigquery_load
  pipeline_uuid: life_expectancy_to_bigquery_load
  schedule_interval: 15 12 * 4 *
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-03-30 12:00:00
  status: active
  variables: {}
